spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_ejemplo?serverTimezone=UTC
        username: root
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
    jpa:  
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
        